import {createTheme} from '@shopify/restyle';

const palette = {
  primaryBlack: '#01090F',
  darkNightBlue: '#01192C',
  darkGrey: '#2B2D30',
  grey: '#414A4C',
  primaryWhite: '#FFFFFF',
  offWhite: '#f8f9fa',
  lightSilver: '#EAEDF1',
  dangerRed: '#ED4956',
  successGreen: '#59D785',
  darkSilver: '#56595E',
  lightGrey: '#9DA0A5',
  silver: '#A5AAAD',
  transparentLightBlack: 'rgba(0, 0, 0, 0.18)',
  facebook: '#1778F2',
  facebookDark: '#0C3568',
  apple: '#414A4C',
  appleDark: '#141818',
  appleDarker: '#0E1111',
  google: '#D54E21',
  googleDark: '#5E0000',
  lightWhite: '#FCFCFC',
  interactionsIconsShadow: 'rgba(0,0,0,0.4)',
  // others:
  lightBlue: '#25CEDC',
};

const theme = createTheme({
  colors: {
    black: palette.primaryBlack,
    white: palette.primaryWhite,
    danger: palette.dangerRed,
    textTitle: palette.primaryBlack,
    textTitleH2: palette.darkGrey,
    inputTitle: palette.darkGrey,
    textParagraph: palette.darkNightBlue,
    buttonTitle: palette.primaryWhite,
    primaryButtonBackground: palette.primaryBlack,
    secondaryButtonBackground: palette.lightSilver,
    tabProfilebuttonTitle: palette.primaryBlack,
    tabProfilebuttonTitleFocused: palette.grey,
    lightButtonBackground: palette.offWhite,
    lightButtonTitle: palette.darkGrey,
    avatarBorderColor: palette.lightSilver,
    avatarBackground: palette.silver,
    avatarProfileBorderColor: palette.darkGrey,
    avatarPlaceholderBackground: palette.darkSilver,
    transparentLightBlack: palette.transparentLightBlack,
    postUserName: palette.primaryWhite,
    postDescription: palette.offWhite,
    subPostUserName: palette.offWhite,
    interactionsIconsColor: palette.lightSilver,
    screenBackground: palette.primaryWhite,
    bottomSheetBackground: palette.primaryWhite,
    textLogo: palette.primaryBlack,
    orSpacerLine: palette.lightSilver,
    facebook: palette.facebook,
    apple: palette.apple,
    google: palette.google,
    socialButtonText: palette.offWhite,
    orSpacerColor: palette.darkGrey,
    inputBorderColor: palette.lightGrey,
    inputBackgroundColor: palette.offWhite,
    headerTintColor: palette.primaryBlack,
    searchInputBackgroundColor: palette.offWhite,
    tabbarInactiveColor: palette.lightGrey,
    tabbarActiveColor: palette.darkGrey,
    success: palette.successGreen,
    lightBlue: palette.lightBlue,
    offWhite: palette.offWhite,
    transparent: 'transparent',
  },
  spacing: {
    auto: 'auto',
    xxs: 2.5,
    xs: 5,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 40,
    xxl: 80,
  },
  borderRadii: {
    xs: 5,
    ss: 7,
    s: 9,
    ssm: 11.5,
    sm: 12,
    m: 16,
    l: 30,
    xl: 50,
    xxl: 60,
  },
  breakpoints: {
    phone: 0,
    tablet: 768,
  },

  textVariants: {
    defaults: {
      fontSize: 14,
      lineHeight: 19,
      color: 'black',
      fontFamily: 'Outfit-Regular',
    },
    input: {
      fontFamily: 'Outfit-Medium',
      fontSize: 14,
      lineHeight: 19,
      letterSpacing: 0.5,
    },
    title: {
      fontSize: 20,
      lineHeight: 28,
      color: 'textTitle',
      fontFamily: 'Outfit-Bold',
    },
    profileUsername: {
      fontSize: 18,
      lineHeight: 25,
      color: 'textTitle',
      fontFamily: 'Outfit-Bold',
    },
    title_h2: {
      fontSize: 18,
      lineHeight: 25,
      color: 'textTitleH2',
      fontFamily: 'Outfit-Medium',
      opacity: 0.95,
    },
    inputTitle: {
      fontSize: 15,
      lineHeight: 18,
      color: 'inputTitle',
    },
    paragraph: {
      fontSize: 14,
      lineHeight: 16,
      color: 'textParagraph',
    },
    paragraphMedium: {
      fontSize: 14,
      lineHeight: 19,
      fontFamily: 'Outfit-SemiBold',
      color: 'textParagraph',
    },
    tiny: {
      fontSize: 13,
      lineHeight: 18,
      color: 'textParagraph',
    },
    buttonTitle: {
      fontSize: 15,
      lineHeight: 20,
      color: 'buttonTitle',
      fontFamily: 'Outfit-SemiBold',
    },
    lightButtonTitle: {
      fontSize: 15,
      lineHeight: 22,
      fontFamily: 'Outfit-SemiBold',
      color: 'lightButtonTitle',
    },
    tabProfilebuttonTitle: {
      fontSize: 14,
      lineHeight: 19,
      color: 'tabProfilebuttonTitle',
      fontFamily: 'Outfit-SemiBold',
    },
    tabProfilebuttonTitleFocused: {
      fontSize: 14,
      lineHeight: 19,
      fontFamily: 'Outfit-SemiBold',
      color: 'tabProfilebuttonTitleFocused',
    },

    postUserName: {
      fontSize: 16,
      lineHeight: 22,
      color: 'postUserName',
      fontFamily: 'Outfit-SemiBold',
    },
    subPostUserName: {
      fontSize: 13,
      lineHeight: 18,
      color: 'subPostUserName',
      fontFamily: 'Outfit-Medium',
    },
    postDescription: {
      fontSize: 14.25,
      lineHeight: 20.3,
      color: 'postDescription',
      fontFamily: 'Outfit-Regular',
      textAlign: 'left',
    },
    textLogo: {
      fontSize: 14,
      lineHeight: 19,
      color: 'textLogo',
    },
    socialButtonText: {
      fontSize: 15,
      lineHeight: 21,
      color: 'socialButtonText',
    },
    orSpacer: {
      fontSize: 14,
      lineHeight: 19,
      color: 'orSpacerColor',
    },
  },
});

const darkTheme: Theme = {
  ...theme,
  colors: {
    ...theme.colors,
    screenBackground: palette.primaryBlack,
    bottomSheetBackground: palette.appleDark,
    buttonTitle: palette.primaryBlack,
    lightButtonTitle: palette.offWhite,
    textTitle: palette.primaryWhite,
    textTitleH2: palette.offWhite,
    textParagraph: palette.lightSilver,
    primaryButtonBackground: palette.primaryWhite,
    secondaryButtonBackground: palette.darkGrey,
    lightButtonBackground: palette.darkGrey,
    avatarBorderColor: palette.darkGrey,
    avatarProfileBorderColor: palette.silver,
    avatarPlaceholderBackground: palette.darkGrey,
    avatarBackground: palette.darkGrey,
    textLogo: palette.offWhite,
    orSpacerLine: palette.darkGrey,
    facebook: palette.facebookDark,
    apple: palette.appleDark,
    google: palette.googleDark,
    orSpacerColor: palette.silver,
    inputBorderColor: palette.grey,
    inputBackgroundColor: palette.appleDarker,
    searchInputBackgroundColor: palette.appleDark,
    headerTintColor: palette.primaryWhite,
    tabProfilebuttonTitle: palette.primaryWhite,
    tabProfilebuttonTitleFocused: palette.offWhite,
    inputTitle: palette.silver,
    tabbarInactiveColor: palette.silver,
    tabbarActiveColor: palette.offWhite,
    offWhite: palette.appleDarker,
  },
};

export type Theme = typeof theme;
export {theme, darkTheme, palette};
